"""add unique constraint to username

Revision ID: 5030165f0211
Revises: 21aed19b1fed
Create Date: 2026-06-29 16:19:47.655072

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5030165f0211"
down_revision: Union[str, Sequence[str], None] = "21aed19b1fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_username", "users", type_="unique")
    # ### end Alembic commands ###
