"""add routine_set table and remove sets/reps/target_weight from routine_exercise

Revision ID: d1b4acfc0db9
Revises: 29b52d6add86
Create Date: 2026-07-02 02:50:49.737691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b4acfc0db9'
down_revision: Union[str, Sequence[str], None] = '29b52d6add86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('routine_exercise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('set_type', sa.Enum('WARM_UP', 'NORMAL', 'DROP_SET', 'FAILURE', name='settype'), nullable=False),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('routine_exercises', 'target_weight')
    op.drop_column('routine_exercises', 'sets')
    op.drop_column('routine_exercises', 'reps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_exercises', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('routine_exercises', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('routine_exercises', sa.Column('target_weight', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.drop_table('routine_sets')
    # ### end Alembic commands ###
